In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as st

from sqlalchemy import create_engine
from sqlalchemy.dialects.postgresql import insert

engine = create_engine('postgresql://Jay:Jay@localhost/JaysDB')

In [ ]:
# Study data files
departments_path = "data/departments.csv"
dept_emp_path = "data/dept_emp.csv"
dept_manager_path = "data/dept_manager.csv"
employees_path = "data/employees.csv"
salaries_path = "data/salaries.csv"
titles_path = "data/titles.csv"

In [ ]:
# Read the various data files
departments_df = pd.read_csv(departments_path)
dept_emp_df = pd.read_csv(dept_emp_path)
dept_manager_df = pd.read_csv(dept_manager_path)
employees_df = pd.read_csv(employees_path)
salaries_df = pd.read_csv(salaries_path)
titles_df = pd.read_csv(titles_path)

#departments_df
#dept_emp_df
#dept_manager_df
#employees_df
#salaries_df
#titles_df

connection = engine.connect()

engine.execute('truncate table "MyBusiness".departments')
#engine.execute('truncate table "MyBusiness".kitty_fro_up')

for index, row in departments_df.iterrows():
    try:
        sql = 'INSERT INTO "MyBusiness".departments(dept_no, dept_name) VALUES('
        sql = sql + "'" + row['dept_no'] + "',"
        sql = sql + "'" + row['dept_name'] + "')"
        engine.execute(sql)
    except Exception as e:
        try:
            errMsg1 = repr(e)[repr(e).index('DETAIL:'):]
             errMsg = errMsg.splitlines()
             errMsg2 = errMsg2.strip('\n')
            errMsg2 = errMsg1.replace("'","")
            errMsg = repr(errMsg2)[repr(errMsg2).index('DETAIL:'):-5]
             errMsg = errMsg2.replace("\n","")
             errMsg = errMsg.replace("\n')","")
#            print('a ' , errMsg)
            print('Nope "MyBusiness".departments ', errMsg )
            sql1 = 'INSERT INTO "MyBusiness".kitty_fro_up(error_message) VALUES('
            sql1 = sql1 + "'" + errMsg + "')"
#            print(sql1)
            engine.execute(sql1)
        except Exception as f:
            print(f)

# close connections
connection.close()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as st

from sqlalchemy import create_engine
from sqlalchemy.dialects.postgresql import insert

engine = create_engine('postgresql://Jay:Jay@localhost/JaysDB')

# Study data files
titles_path = "data/titles.csv"

# Read the various data files
titles_df = pd.read_csv(titles_path)

#titles_df

connection = engine.connect()

engine.execute('truncate table "MyBusiness".titles')
#engine.execute('truncate table "MyBusiness".kitty_fro_up')

    for index, row in departments_df.iterrows():
    try:
        sql = 'INSERT INTO "MyBusiness".titles(title_id, title) VALUES('
        sql = sql + "'" + row['title_id'] + "',"
        sql = sql + "'" + row['title'] + "')"
        engine.execute(sql)
    except Exception as e:
        try:
            errMsg1 = repr(e)[repr(e).index('DETAIL:'):]
            errMsg2 = errMsg1.replace("'","")
            errMsg = repr(errMsg2)[repr(errMsg2).index('DETAIL:'):-5]
#            print('a ' , errMsg)
            print('Nope "MyBusiness".titles ', errMsg )
            sql1 = 'INSERT INTO "MyBusiness".kitty_fro_up(error_message) VALUES('
            sql1 = sql1 + "'" + errMsg + "')"
#            print(sql1)
            engine.execute(sql1)
        except Exception as f:
            print(f)

# close connections
connection.close()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as st

from sqlalchemy import create_engine
from sqlalchemy.dialects.postgresql import insert

engine = create_engine('postgresql://Jay:Jay@localhost/JaysDB')

# Study data files
titles_path = "data/salaries.csv"

# Read the various data files
titles_df = pd.read_csv(titles_path)

#print(salaries_df)

connection = engine.connect()

engine.execute('truncate table "MyBusiness".salaries')
#engine.execute('truncate table "MyBusiness".kitty_fro_up')

    for index, row in departments_df.iterrows():
    try:
        sql = 'INSERT INTO "MyBusiness".salaries(emp_no, salary) VALUES('
        sql = sql + "'" + row['title_id'] + "',"
        sql = sql + "'" + row['title'] + "')"
        engine.execute(sql)
    except Exception as e:
        try:
            errMsg1 = repr(e)[repr(e).index('DETAIL:'):]
            errMsg2 = errMsg1.replace("'","")
            errMsg = repr(errMsg2)[repr(errMsg2).index('DETAIL:'):-5]
#            print('a ' , errMsg)
            print('Nope "MyBusiness".salaries ', errMsg )
            sql1 = 'INSERT INTO "MyBusiness".kitty_fro_up(error_message) VALUES('
            sql1 = sql1 + "'" + errMsg + "')"
#            print(sql1)
            engine.execute(sql1)
        except Exception as f:
            print(f)

# close connections
connection.close()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as st

from sqlalchemy import create_engine
from sqlalchemy.dialects.postgresql import insert

engine = create_engine('postgresql://Jay:Jay@localhost/JaysDB')

# Study data files
titles_path = "data/dept_emp.csv"

# Read the various data files
titles_df = pd.read_csv(titles_path)

#print(dept_emp_df)

connection = engine.connect()

engine.execute('truncate table "MyBusiness".dept_emp')
#engine.execute('truncate table "MyBusiness".kitty_fro_up')

    for index, row in departments_df.iterrows():
    try:
        sql = 'INSERT INTO "MyBusiness".salaries(emp_no, dept_no) VALUES('
        sql = sql + "'" + row['title_id'] + "',"
        sql = sql + "'" + row['title'] + "')"
        engine.execute(sql)
    except Exception as e:
        try:
            errMsg1 = repr(e)[repr(e).index('DETAIL:'):]
            errMsg2 = errMsg1.replace("'","")
            errMsg = repr(errMsg2)[repr(errMsg2).index('DETAIL:'):-5]
#            print('a ' , errMsg)
            print('Nope "MyBusiness".dept_emp ', errMsg )
            sql1 = 'INSERT INTO "MyBusiness".kitty_fro_up(error_message) VALUES('
            sql1 = sql1 + "'" + errMsg + "')"
#            print(sql1)
            engine.execute(sql1)
        except Exception as f:
            print(f)

# close connections
connection.close()

# emp_no    dept_no

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as st

from sqlalchemy import create_engine
from sqlalchemy.dialects.postgresql import insert

engine = create_engine('postgresql://Jay:Jay@localhost/JaysDB')

# Study data files
titles_path = "data/dept_manager.csv"

# Read the various data files
titles_df = pd.read_csv(titles_path)

#print(dept_emp_df)

connection = engine.connect()

engine.execute('truncate table "MyBusiness".dept_manager')
#engine.execute('truncate table "MyBusiness".kitty_fro_up')

    for index, row in departments_df.iterrows():
    try:
        sql = 'INSERT INTO "MyBusiness".salaries(dept_no, emp_no) VALUES('
        sql = sql + "'" + row['title_id'] + "',"
        sql = sql + "'" + row['title'] + "')"
        engine.execute(sql)
    except Exception as e:
        try:
            errMsg1 = repr(e)[repr(e).index('DETAIL:'):]
            errMsg2 = errMsg1.replace("'","")
            errMsg = repr(errMsg2)[repr(errMsg2).index('DETAIL:'):-5]
#            print('a ' , errMsg)
            print('Nope "MyBusiness".dept_manager ', errMsg )
            sql1 = 'INSERT INTO "MyBusiness".kitty_fro_up(error_message) VALUES('
            sql1 = sql1 + "'" + errMsg + "')"
#            print(sql1)
            engine.execute(sql1)
        except Exception as f:
            print(f)

# close connections
connection.close()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as st

from sqlalchemy import create_engine
from sqlalchemy.dialects.postgresql import insert

engine = create_engine('postgresql://Jay:Jay@localhost/JaysDB')

# Study data files
titles_path = "data/employees.csv"

# Read the various data files
titles_df = pd.read_csv(titles_path)

#print(employees_df)

connection = engine.connect()

engine.execute('truncate table "MyBusiness".employees')
#engine.execute('truncate table "MyBusiness".kitty_fro_up')

for index, row in employees_df.iterrows():
    try:
        sql = 'INSERT INTO "MyBusiness".employees(emp_no, emp_title_id, birth_date, first_name, last_name, sex, hire_date) VALUES('
#        sql = sql + repr(row['emp_no'])
        sql = sql + "'" + repr(row['emp_no']) + "',"
        sql = sql + "'" + row['emp_title_id'] + "',"
        sql = sql + "'" + row['birth_date'] + "',"
        sql = sql + "'" + row['first_name'] + "',"
        sql = sql + "'" + row['last_name'] + "',"
        sql = sql + "'" + row['sex'] + "',"
        sql = sql + "'" + row['hire_date'] + "')"
        engine.execute(sql)
#        connection.commit()
#        print(sql)
    except Exception as e:
        try:
            print(e)
#            errMsg1 = repr(e)[repr(e).index('DETAIL:'):]
            errMsg2 = errMsg1.replace("'","")
            errMsg = repr(errMsg2)[repr(errMsg2).index('DETAIL:'):-5]
            print('Nope "MyBusiness".employees ', errMsg )
            sql1 = 'INSERT INTO "MyBusiness".kitty_fro_up(error_message) VALUES('
            sql1 = sql1 + "'" + errMsg + "')"
#            print(sql1)
            engine.execute(sql1)
#            connection.commit()
        except Exception as f:
            z = 1
#            print(f)

# close connections
connection.close()

# emp_no    emp_title_id    birth_date    first_name   last_name   sex hire_date

In [ ]:
# departments
import pandas as pd

from sqlalchemy import create_engine

engine = create_engine('postgresql://Jay:Jay@localhost/JaysDB')

connection = engine.connect()


# departments
SQL_Query = pd.read_sql_query(
'''SELECT dept_no, dept_name
FROM "MyBusiness".departments;''', connection)

departments_DF = pd.DataFrame(SQL_Query, columns=['dept_no','dept_name'])
#print (departments_df)


# dept_emp
SQL_Query = pd.read_sql_query(
'''SELECT emp_no, dept_no
FROM "MyBusiness".dept_emp;''', connection)

dept_emp_DF = pd.DataFrame(SQL_Query, columns=['emp_no', 'dept_no'])
#print (dept_emp_df)


# dept_manager
SQL_Query = pd.read_sql_query(
'''SELECT dept_no, emp_no
FROM "MyBusiness".dept_manager;''', connection)

dept_manager_DF = pd.DataFrame(SQL_Query, columns=['dept_no', 'emp_no'])
#print (dept_manager_DF)\n",


# dept_manager
SQL_Query = pd.read_sql_query(
'''SELECT emp_no, emp_title_id, birth_date, first_name, last_name, sex, hire_date
FROM "MyBusiness".employees;''', connection)

employees_DF = pd.DataFrame(SQL_Query, columns=['emp_no', 'emp_title_id', 'birth_date', 'first_name', 'last_name', 'sex', 'hire_date'])
#print (employees_DF)


# salaries
SQL_Query = pd.read_sql_query(
'''SELECT emp_no, salary
    FROM "MyBusiness".salaries;''', connection)

salaries_DF = pd.DataFrame(SQL_Query, columns=['emp_no', 'salary'])
#print (salaries_DF)


# titles
SQL_Query = pd.read_sql_query(
'''SELECT title_id, title
FROM "MyBusiness".titles;;''', connection)

titles_DF = pd.DataFrame(SQL_Query, columns=['title_id', 'title'])
print (titles_DF)

# close connections
connection.close()